[package]
name = "parser_jellyfish_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_ecma_parser = { version = "0.102.1", features = [ "typescript" ] }
swc_common = {version = "0.17.0", features = ["tty-emitter"]}
swc_ecma_ast = "0.76.0"
convert_case = "0.5.0"
